# Generated by Django 3.1.1 on 2020-09-20 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='completedate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
